#!/bin/bash -l
# @ shell=/bin/bash
#
# @ error = {{ job_name }}.err.$(jobid)
# @ output = {{ job_name }}.out.$(jobid)
# @ job_type = parallel
# @ node_usage = not_shared
# @ node = {{ n_nodes }}
# @ tasks_per_node = 20
{%- if gpu %}
# @ requirements = (Feature=="gpu")
{%- endif %}
# @ resources = ConsumableCpus(1)
# @ network.MPI = sn_all,not_shared,us
# @ wall_clock_limit = {{ formatted_time }}
# @ queue

module purge
module load {{ module }}
module load cuda
# run {{ module }} for {{ time }} minutes
{%- if mdengine == "gromacs" %}
poe gmx_mpi mdrun -deffnm {{ name }} -maxh {{ time / 60 }}
{%- elif mdengine == "namd" %}
poe namd2 {{ name }}.namd
{%- endif %}
